### ISSUE TITLE
[android] : stop video playing in background

### ISSUE THREAD

**Issue by TVart** [hughred22/Ionic2-Angular2-YouTube-Channel-App#1]
Hi,

I'm curious, have you succeded to publish your app on google play store?
Google don't like that apps enable background playing of YouTube videos.

So in app.ts I've tried to handle pause / stop ( power button ) events then call pauseVideo() on  window['YT'].Player ..
but without success. YT.Player is not available in this scope.

Any idea to work it out ?

Thanks

**Comment by ghost** [comment]
@TVart Did you ever get this solved?

**Comment by JoxieMedina** [comment]
Hi @Darksyntax and anyone who had get this issue , the solution is handle the "pause" event in the android life cycle:

First in the app.js file subscribe to the pause event and emit a event flag:
`  platform.pause.subscribe(()=>{
      console.log('App Paused');
      this.events.publish('App:Paused');
    });
`
then in the constructor of the youtube-service.ts file subscribe to the event created before and pause the video:
`this.events.subscribe('App:Paused', () => {
      this.youtube.player.pauseVideo();
    });`
EDIT: I made a pull request with this issue solved

**Comment by ghost** [comment]
@JoxieMedina  Thank you very much! I hope this helps others!

**Comment by TVart** [comment]
@JoxieMedina thank you, consider issue fixed
